version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm i -g npm@8
      - node -v
      - npm -v
      - npm ci
  build:
    commands:
      - echo "Build started on `date`"
      - npm run build
      - npm run cdk -- deploy --all --require-approval never
      - echo "Branch ${BRANCH}"
  post_build:
    commands:
      - npm run deploy:resources
      - echo "Build completed on `date`"