# This workflow will do a clean install, run linting, the unit test suite, and a test synthesis.

name: PR Check

on:
  pull_request:
    branches: [ master, develop ]

jobs:
  verify:
    runs-on: ubuntu-latest
    env:
      IS_GITHUB: 'true'
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: echo "BRANCH=${GITHUB_BASE_REF}" >> $GITHUB_ENV
    - run: npm ci
    - run: npm run pr-check